### ISSUE TITLE
Use of ontology

### ISSUE THREAD

**Issue by acapop** [universAAL/nativeandroid#481]
How can I use ontology in android (like Health Measurement)? We ontology is light example using is there some link where I can learn how to write metadata and specialy serialization part? Why is somewhere http://ontology.igd.fhg.de/LightingConsumer.owl# being used and some where http://ontology.universAAL.org/uAAL.owl# ?

         <requirement>
            <title>Get all light sources</title>
            <description>SERVICE CALLER REQUEST: Get a list of all light sources.</description>
            <action>org.universaal.nativeandroid.light.CALL_GETLAMPS</action>
            <category>android.intent.category.DEFAULT</category>
            <replyAction>org.universaal.nativeandroid.light.REPLY_GETLAMPS</replyAction>
            <replyCategory>android.intent.category.DEFAULT</replyCategory>
            <remote>true</remote>
            <output>
                <key>http://ontology.igd.fhg.de/LightingConsumer.owl#controlledLamps</key>
                <value>http://ontology.igd.fhg.de/LightingServer.owl#{lamps}</value>
            </output>
            <serialization>
               <![CDATA[
@prefix ns: <http://ontology.igd.fhg.de/LightingConsumer.owl#> .
@prefix pvn: <http://ontology.universAAL.org/uAAL.owl#> .
@prefix : <http://www.daml.org/services/owl-s/1.1/Process.owl#> .
_:BN000000 a pvn:ServiceRequest ;
  pvn:requiredResult [
    :withOutput [
        a :OutputBinding ;
        :toParam ns:controlledLamps ;
        :valueForm """
          @prefix : <http://ontology.universAAL.org/Service.owl#> .
          _:BN000000 a :PropertyPath ;
            :thePath (
              <http://ontology.universaal.org/Lighting.owl#controls>
            ) .
          """^^<http://www.w3.org/1999/02/22-rdf-syntax-ns#XMLLiteral>
      ] ;
    a :Result
  ] ;
  pvn:requestedService [
    a <http://ontology.universaal.org/Lighting.owl#Lighting>
  ] .
ns:controlledLamps a :Output .
]]>
            </serialization>
         </requirement>

**Comment by acapop** [comment]
Also, is there builded ont.health.measurement ontology?

**Comment by Alfiva** [comment]
Here is the link to the wiki explaining how to write the metadata: https://github.com/universAAL/nativeandroid/wiki/Adapting-or-developing-your-app-for-uAAL#Writing_Metadata
However I recommend you familiarize yourself with ontologies and how we use them in uAAL:
https://github.com/universAAL/platform/wiki/Ontologies-%28Quick%29
https://github.com/universAAL/platform/wiki/Ontologies-%28Details%29
https://github.com/universAAL/platform/wiki/Ontologies-%28Advanced%29
You may skip the parts about writing ontologies in code, but they may come in handy because the quickest thing to obtain the serialized metadata is writing the elements (e.g Context Event, Service Profile, etc...) in code and then use the serializer to serialize it, for instance into the console, and then copy/paste it into the xml.

In the gradle branch you will find a collection of Dexed ontologies ready to use in Android uAAL, including ont.health.measurement:
https://github.com/universAAL/nativeandroid/tree/gradle/Files/Configurations/felix/ontologies

**Comment by acapop** [comment]
thank you
