### ISSUE TITLE
Dexing a jar

### ISSUE THREAD

**Issue by ClementBrohon** [universAAL/nativeandroid#5]
I have dexed the device ontology and put in the good folder.

I want now publish something and use the ontology in a context event for example. How the program knows that it can use this ontology? I have to define something and use a particular prefixe for import it?

For now I say simply "@prefix light: <http://ontology.universAAL.org/Device.owl# > "

**Comment by Alfiva** [comment]
Check: https://github.com/universAAL/nativeandroid/wiki/Running-uAAL-in-Android#Ontologies 
If you have just one ontology with no fancy dependencies, putting it in the right folder is enough. If you had multiple ontologies, they have to be read in the proper dependency order. That's what the config files described in the link above are for.

**Comment by Alfiva** [comment]
Forgot to add: you have to use those special config file in the link if you use a custom ontology that does not use the package org.universAAL.ontology

**Comment by ClementBrohon** [comment]
I have only one ontology and I have done this.

So I can just do "<http://ontology.universAAL.org/Device.owl#LightActuator >" and it will work?

I can not look at what is at this adress: @prefix tst: <http://ontology.igd.fhg.de/LightingServer.owl#>. Is a abstract URI for identify or the program will interpreter and transformer this?

**Comment by Alfiva** [comment]
@prefix tst: http://ontology.igd.fhg.de/LightingServer.owl#.
Is just part of the syntax of Turtle (prefix for later URIs), don't worry about it.
If you only need to use our official Device ontology, you just need to place its dexed in jar in the ontologies folder, that's all.

**Comment by Alfiva** [comment]
Sorry, I have been confused with other issues and did not realize your original question was in fact about how to use a certain ontology in what I assume is the serialization of a Context Event.
The serialization of a Context Event is formatted with Turtle, so you have to follow its rules:

-You can use the full URI in your serialization, like
```
...
... <http://ontology.universAAL.org/Device.owl#LightActuator> ...
...
```

OR

-You can use a prefix, defining the prefix at the begining. Prefixes are just syntactic sugar, they are for shortening URIs later. Like:
```
@prefix dev: http://ontology.universAAL.org/Device.owl#.
...
... dev:LightActuator ...
...
```
That said, everything I pointed out before about including the Device ontology dexed jar still applies, since the Device ontology is not included by default.

**Comment by ClementBrohon** [comment]
Thank you :)

**Comment by ClementBrohon** [comment]
It seems that I have failed to dexer my ontology

However I feel that I followed the tutorial. I will try to show what I did, in the worst case it can still be used as a video tutorial. With IntelliJ I have a result, but it doesn't work. With Eclipse I can't dex.
 

**Step One: Convert to jar format With IntelliJ**
![step1intelij](https://cloud.githubusercontent.com/assets/25262825/26674988/889ab29c-46c2-11e7-9651-b38e34944938.gif)

**I already notice that the two jar do not at all the same weight**

**Step One: Convert to jar format With Eclipse**
![step1eclipse](https://cloud.githubusercontent.com/assets/25262825/26675006/96d37c86-46c2-11e7-8f20-a5b046657a41.gif)

**Step Two: jar to dex With IntelliJ**
![step2intelij](https://cloud.githubusercontent.com/assets/25262825/26675042/acc4b9ba-46c2-11e7-9404-3dcbe8cce13d.gif)

**Step Two: jar to dex With Eclipse**
![step2eclipse](https://cloud.githubusercontent.com/assets/25262825/26675062/bf8dc154-46c2-11e7-8703-be556408bcee.gif)

**Step Three: Add dex to jar With IntelliJ**
![step3intelij](https://cloud.githubusercontent.com/assets/25262825/26675083/d006797c-46c2-11e7-8df4-de5b95f1a9e9.gif)

**Step Four: Put in the file With IntelliJ**
![image](https://cloud.githubusercontent.com/assets/25262825/26675121/fb2fac40-46c2-11e7-8952-a42bb4f4b4ac.png)


**Result in log**
![image](https://cloud.githubusercontent.com/assets/25262825/26675278/a44679c6-46c3-11e7-9809-14ba804c73bd.png)


UniversAAl starts anyways, but I suspect that one of my crashes comes from there.

**Comment by Alfiva** [comment]
Let me go step by step because there are a lot of things here
-Ont.device, like all regular projects in universAAL, is a Maven project. You generate the jar by executing Maven install. I do not respond for how well it will work if you build it with anything else.
-You don't actually need to build ont.device, you can get all our latests jars from our nexus repository, like http://depot.universaal.org/nexus/content/repositories/snapshots/org/universAAL/ontology/ont.device/3.4.1-SNAPSHOT/ 
-I take it you are dexing from the console, regardless of IntelliJ or Eclipse.
-You can check a properly dexed jar if you open it with e.g. WinRaR and it has classes.dex inside.
-Here is a code I use to create a .bat batch script for windows that dexes all jars in the folder you put it (create txt file, put this code in, save file, change extension to .bat, put it in folder where the jar is, execute it)

```
for %%f in (*.jar) do (
call C:\Proyectos\Android\sdk\build-tools\23.0.3\dx --dex --output=%cd%\classes.dex %cd%\%%~nf.jar
call C:\Proyectos\Android\sdk\build-tools\23.0.3\aapt add %%~nf.jar classes.dex
del classes.dex
)
```

(Of course, change the path tot he dx and aapt binaries to yours)

-Make sure you push the dexed jar into the ...data/felix/ontologies folder in the phone. Fromt he screenshot you pasted looks like it is there, but there was a problem because of incorrect dexing.

**Comment by Alfiva** [comment]
To speed things up, I have uploaded a dexed version of our latest ont.device jar in https://github.com/universAAL/nativeandroid/tree/master/Files/Configurations/felix/ontologies
